name: Deploy on Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'alvin1904/ghostchats-client'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install vercel cli
        run: npm install -global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --name "ghostchats" --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
